name: CI
on: [push]
jobs:
  build:
    name: Build and lint
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./docs

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
